[package]
name = "onc-rpc"
version = "0.1.0"
authors = ["Janito Vaqueiro Ferreira Filho <janito.vff@gmail.com>"]

[dependencies]
bytes = "0.4"
error-chain = "0.11"
serde = "1.0"
serde_derive = "1.0"
serde-xdr = { git = "https://github.com/jvff/serde-xdr.git" }
